services:
  # --- Clientes ---
  clientes-service:
    build:
      context: ./services/clientes-service
      dockerfile: Dockerfile
    env_file:
      - ./services/clientes-service/.env
    ports:
      - "3001:3000"
    networks:
      - microservices-network
    depends_on:
      - clientes-db

  clientes-db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: clientes
    volumes:
      - clientes-data:/var/lib/mysql
    networks:
      - microservices-network

  # --- Productos ---
  productos-service:
    build:
      context: ./services/productos-service
      dockerfile: Dockerfile
    env_file:
      - ./services/productos-service/.env
    ports:
      - "3002:3000"
    networks:
      - microservices-network
    depends_on:
      - productos-db

  productos-db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: productos
    volumes:
      - productos-data:/var/lib/mysql
    networks:
      - microservices-network

  # --- Ventas ---
  ventas-service:
    build:
      context: ./services/ventas-service
      dockerfile: Dockerfile
    env_file:
      - ./services/ventas-service/.env
    ports:
      - "3003:3000"
    networks:
      - microservices-network
    depends_on:
      - ventas-db

  ventas-db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: ventas
    volumes:
      - ventas-data:/var/lib/mysql
    networks:
      - microservices-network

  # nginx para servir
  nginx:
    image: nginx:latest
    volumes:
      - ./infra/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - clientes-service
      - productos-service
      - ventas-service
    networks:
      - microservices-network




# --- Redes y vol√∫menes ---
networks:
  microservices-network:
    driver: bridge

volumes:
  clientes-data:
  productos-data:
  ventas-data:
